title: Whenfung                 # title of the site
description: 个人网站            # description of the site
url: https://whenfung.github.io # domain
baseurl: ""                 # root directory

# Path of site resources
img: /assets/img
css: /assets/css

## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# default layout of the articles in _posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

disqus: whenfung
email: whenfung@gmail.com

socials:
- name: github
  url: https://github.com/whenfung
- name: twitter
  url: https://twitter.com/denglate


nav:
- name: Home
  path: /
- name: Project
  path: /pages/project.html
- name: About
  path: /pages/about.html
